### ISSUE TITLE
Create a proper release of lipstick

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/aaf-lipstick#69]
It has been way to long since we released lipstick as a proper gem, by now we're certainly in 2.0 land.

Once a new release has been made add an issue to every project using lipstick via Git + develop branch advising them to point directly to the gem instead.

**Comment by bradleybeddoes** [comment]
Will need some co-ordination with rest of the dev team to ensure they're comfortable with timing etc.

**Comment by smangelsdorf** [comment]
Everything on our side is comfortable with 2.0.0 being tagged. The gem has stabilised now since the new branding stuff was merged, and plenty of projects are using the `develop` branch without hassle.

The only thing I see coming early in the 2.x versions is some work on compatibility with Content-Security-Policy, if we hit any other issues there.

**Comment by rcaught** [comment]
All the projects using Lipstick either have pull requests or issues to move to v2.0.0.
